# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.FloatField(default=0.0, verbose_name=' Mean of the Normal Distribution')),
                ('s', models.FloatField(default=1.0, verbose_name=' Standard Deiation of the Normal Distribution')),
            ],
        ),
    ]
