# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample_Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField(default=1.0, verbose_name=' Number of samples you wish to draw:')),
            ],
        ),
    ]
